[package]
name = "seagrass-anchor-v1"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Anchor v1 framework catalog for Seagrass"

[dependencies]
seagrass-core = { package = "seagrass", path = "../.." }
seagrass-framework = { path = "../seagrass-framework" }
