//! Completions for `module::VALUE` and `crate::VALUE` constraint expressions.
//!
//! The associated-value completer (`associated_values`) only fires for
//! PascalCase *type* paths such as `State::INIT_SPACE`. Idiomatic Anchor program
//! addresses are written against lowercase **module** roots instead —
//! `address = token::ID`, `address = mpl_token_metadata::ID`, `address =
//! crate::ID`. The diagnostic side already accepts those (any path whose root
//! segment is an imported name or a crate-relative root resolves), so this
//! module restores parity by *offering* the same idioms the diagnostic accepts.

use {
    crate::document::ParsedDocument,
    tower_lsp::lsp_types::{CompletionItem, CompletionItemKind},
};

const PATH_SEPARATOR: &str = "::";
/// The program-address constant every Solana program crate/module exposes
/// (`declare_id!` generates it; `anchor_spl` modules re-export it).
const PROGRAM_ID_ASSOCIATED_CONST: &str = "ID";
/// The function form generated by `declare_id!` / exposed by the `Id` trait.
const PROGRAM_ID_FUNCTION: &str = "id";
/// Path roots that resolve against the current crate rather than an import.
const CRATE_RELATIVE_PATH_ROOTS: &[&str] = &["crate", "self", "super"];

/// A `<owner>::<value_prefix>` split where `owner` is a module or crate-relative
/// path (as opposed to the PascalCase type paths handled by `associated_values`).
pub(super) struct ModulePathPrefix<'a> {
    owner_path: &'a str,
    pub(super) value_prefix: &'a str,
}

pub(super) fn module_path_prefix<'a>(
    document: &ParsedDocument,
    value_prefix: &'a str,
) -> Option<ModulePathPrefix<'a>> {
    let (owner_path, value_prefix) = value_prefix.rsplit_once(PATH_SEPARATOR)?;
    is_module_or_crate_relative_path(document, owner_path).then_some(ModulePathPrefix {
        owner_path,
        value_prefix,
    })
}

pub(super) fn filter_prefix<'a>(
    document: &ParsedDocument,
    value_prefix: &'a str,
) -> Option<&'a str> {
    module_path_prefix(document, value_prefix).map(|prefix| prefix.value_prefix)
}

pub(super) fn module_path_value_items(
    document: &ParsedDocument,
    value_prefix: &str,
) -> Vec<CompletionItem> {
    let Some(prefix) = module_path_prefix(document, value_prefix) else {
        return Vec::new();
    };

    let mut items = Vec::new();
    if offers_program_id_constant(document, prefix.owner_path) {
        items.push(program_id_item());
        items.push(program_id_function_item());
    }
    if is_crate_relative_path(prefix.owner_path) {
        items.extend(crate_relative_value_items(document));
    }

    items.sort_by(|left, right| left.sort_text.cmp(&right.sort_text));
    items.dedup_by(|left, right| left.label == right.label);
    items
}

/// `token::ID`, `mpl_token_metadata::ID`, and `anchor_spl::token::ID` all name
/// the program address constant. We offer `ID` whenever the owner root is an
/// imported module, and for crate-relative roots only when a `declare_id!` is
/// present (mirroring the diagnostic's resolution rule).
fn offers_program_id_constant(document: &ParsedDocument, owner_path: &str) -> bool {
    if is_crate_relative_path(owner_path) {
        return document.symbols().declared_program_id.is_some();
    }
    owner_root_is_imported(document, owner_path)
}

fn crate_relative_value_items(document: &ParsedDocument) -> Vec<CompletionItem> {
    document
        .symbols()
        .value_items
        .iter()
        .map(|value| CompletionItem {
            label: value.name.clone(),
            kind: Some(CompletionItemKind::VALUE),
            detail: Some("Crate-local value in scope".to_string()),
            sort_text: Some(format!("020_anchor_module_value_{}", value.name)),
            data: Some(serde_json::json!({
                "anchorCompletion": "constraint-expression-value",
                "constraintExpressionValueKind": "crate-relative-value",
            })),
            ..CompletionItem::default()
        })
        .collect()
}

fn program_id_item() -> CompletionItem {
    CompletionItem {
        label: PROGRAM_ID_ASSOCIATED_CONST.to_string(),
        kind: Some(CompletionItemKind::CONSTANT),
        detail: Some("Program address constant".to_string()),
        sort_text: Some(format!(
            "000_anchor_module_program_id_{PROGRAM_ID_ASSOCIATED_CONST}"
        )),
        preselect: Some(true),
        data: Some(serde_json::json!({
            "anchorCompletion": "associated-value",
            "associatedValueKind": "const",
        })),
        ..CompletionItem::default()
    }
}

/// The `id()` function form (`token::id()`, `crate::id()`). `declare_id!`
/// generates both an `ID` const and an `id()` fn, and `anchor_lang::Id` /
/// `SysvarId` expose `id()`; offering both keeps the path complete.
fn program_id_function_item() -> CompletionItem {
    CompletionItem {
        label: format!("{PROGRAM_ID_FUNCTION}()"),
        kind: Some(CompletionItemKind::FUNCTION),
        detail: Some("Program address accessor".to_string()),
        insert_text: Some(format!("{PROGRAM_ID_FUNCTION}()")),
        sort_text: Some(format!(
            "001_anchor_module_program_id_{PROGRAM_ID_FUNCTION}"
        )),
        data: Some(serde_json::json!({
            "anchorCompletion": "associated-value",
            "associatedValueKind": "function",
        })),
        ..CompletionItem::default()
    }
}

fn is_module_or_crate_relative_path(document: &ParsedDocument, owner_path: &str) -> bool {
    is_identifier_path(owner_path)
        && (is_crate_relative_path(owner_path) || owner_root_is_imported(document, owner_path))
}

fn is_crate_relative_path(owner_path: &str) -> bool {
    path_root(owner_path).is_some_and(|root| CRATE_RELATIVE_PATH_ROOTS.contains(&root))
}

fn owner_root_is_imported(document: &ParsedDocument, owner_path: &str) -> bool {
    let Some(root) = path_root(owner_path) else {
        return false;
    };
    document
        .symbols()
        .imported_names
        .iter()
        .any(|import| import.name == root)
}

fn path_root(owner_path: &str) -> Option<&str> {
    owner_path.split(PATH_SEPARATOR).next()
}

/// Every `::`-separated segment must be a bare Rust identifier. This excludes
/// the PascalCase type paths and method-call receivers handled elsewhere only
/// incidentally; its real job is to reject malformed prefixes (empty segments,
/// stray punctuation) before we treat the string as a module path.
fn is_identifier_path(owner_path: &str) -> bool {
    !owner_path.is_empty()
        && owner_path.split(PATH_SEPARATOR).all(|segment| {
            let mut chars = segment.chars();
            chars
                .next()
                .is_some_and(|ch| ch.is_ascii_alphabetic() || ch == '_')
                && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
        })
}
