[package]
name = "seagrass-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
rust-version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
seagrass = { path = "..", version = "1.0.2" }
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_document_parse"
path = "fuzz_targets/fuzz_document_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_anchor_attr"
path = "fuzz_targets/fuzz_anchor_attr.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_manifest_parse"
path = "fuzz_targets/fuzz_manifest_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_semantic_diagnostics"
path = "fuzz_targets/fuzz_semantic_diagnostics.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_anchor_preflight"
path = "fuzz_targets/fuzz_anchor_preflight.rs"
test = false
doc = false
bench = false
