[package]
name = "seagrass-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Installable Seagrass language-server entrypoint"

[[bin]]
name = "seagrass"
path = "src/main.rs"

[dependencies]
seagrass-core = { package = "seagrass", path = "../..", version = "1.0.2" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
