[package]
name = "seagrass-native"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Native Solana framework boundary for Seagrass"

[dependencies]
seagrass-framework = { path = "../seagrass-framework" }
