//! Facts about what pinned macro/library versions emit. Review on every Anchor
//! version bump alongside the generated catalogs.

/// Anchor account discriminator associated const emitted for `#[account]`
/// types by the pinned Anchor support catalogs (`anchor-v1` 1.0.2 and
/// `anchor-v2-preview` 2.0.0).
pub(crate) const ACCOUNT_DISCRIMINATOR_ASSOCIATED_CONST: &str = "DISCRIMINATOR";

/// Conventional discriminator field name used by Anchor account validation
/// code and preserved by the pinned Anchor support catalogs.
pub(crate) const ACCOUNT_DISCRIMINATOR_FIELD: &str = "discriminator";

/// Names that signal an explicit account discriminator check.
pub(crate) const ACCOUNT_DISCRIMINATOR_NAMES: &[&str] = &[
    ACCOUNT_DISCRIMINATOR_ASSOCIATED_CONST,
    ACCOUNT_DISCRIMINATOR_FIELD,
];

/// Closed-account sentinel emitted by Anchor's account close helpers in the
/// pinned Anchor support catalogs.
pub(crate) const CLOSED_ACCOUNT_DISCRIMINATOR: &str = "CLOSED_ACCOUNT_DISCRIMINATOR";

/// `InitSpace` associated const emitted by Anchor derive support in the pinned
/// Anchor support catalogs.
pub(crate) const INIT_SPACE_ASSOCIATED_CONST: &str = "INIT_SPACE";

/// Program ID declaration macro parsed by the pinned Anchor syntax support
/// (`anchor-syn` 1.0.2, rev 4addac5304bf2d2378448e86b5ee374c99037585).
pub(crate) const DECLARE_ID_MACRO: &str = "declare_id";

/// Classic Anchor program declaration invocation used by native-project
/// classification. Kept separate from [`PROGRAM_DECLARATION_MACROS`] so
/// `declare_program!` is not treated as a native Solana entrypoint shortcut
/// without a false-positive audit.
pub(crate) const DECLARE_ID_MACRO_INVOCATION: &str = "declare_id!";

/// Anchor v2 program declaration macro name kept as a declaration idiom. Do
/// not use it for project framework classification without a false-positive
/// audit.
pub(crate) const DECLARE_PROGRAM_MACRO: &str = "declare_program";

/// Macro names that declare an Anchor program in parsed document context.
pub(crate) const PROGRAM_DECLARATION_MACROS: &[&str] = &[DECLARE_ID_MACRO, DECLARE_PROGRAM_MACRO];

/// Anchor CPI context type from the pinned Anchor support catalogs.
pub(crate) const CPI_CONTEXT_TYPE: &str = "CpiContext";

/// Anchor CPI constructor without signer seeds.
pub(crate) const CPI_CONTEXT_NEW_METHOD: &str = "new";

/// Anchor CPI constructor with signer seeds.
pub(crate) const CPI_CONTEXT_NEW_WITH_SIGNER_METHOD: &str = "new_with_signer";

/// Solana CPI invocation helper from `solana-program` 2.2.1.
pub(crate) const SOLANA_INVOKE_FUNCTION: &str = "invoke";

/// Anchor account refresh method emitted by `Account`-like wrappers in the
/// pinned Anchor support catalogs.
pub(crate) const ACCOUNT_RELOAD_METHOD: &str = "reload";

/// Safe Anchor account deserializer generated by the pinned Anchor support
/// catalogs.
pub(crate) const TRY_DESERIALIZE_METHOD: &str = "try_deserialize";

/// Anchor deserializers that include discriminator checks.
pub(crate) const SAFE_DESERIALIZE_METHODS: &[&str] = &[TRY_DESERIALIZE_METHOD];

/// Raw deserializer that bypasses Anchor's discriminator check.
pub(crate) const TRY_DESERIALIZE_UNCHECKED_METHOD: &str = "try_deserialize_unchecked";

/// Raw Borsh / Anchor deserializers that must be paired with discriminator
/// checks. Pinned to Borsh 0.10.4/1.6.1 and the Anchor support catalogs.
pub(crate) const RAW_DESERIALIZE_METHODS: &[&str] = &[
    "try_from_slice",
    "deserialize",
    TRY_DESERIALIZE_UNCHECKED_METHOD,
    "from_account_info",
];

/// SPL token unpack helpers exposed through the Solana `Pack` idiom and token
/// account wrappers in the pinned support/corpus set.
pub(crate) const TOKEN_ACCOUNT_UNPACK_METHODS: &[&str] =
    &["unpack", "unpack_unchecked", "unpack_from_slice"];

/// Token account container type names used by SPL token and token-2022 account
/// wrappers in the pinned support/corpus set.
pub(crate) const TOKEN_ACCOUNT_UNPACK_TYPES: &[&str] = &[
    "Account",
    "TokenAccount",
    "SplTokenAccount",
    "StateWithExtensions",
];

pub(crate) fn ident_is_any(ident: &syn::Ident, names: &[&str]) -> bool {
    names.iter().any(|name| ident == *name)
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    const SOURCE_ROOT: &str = "src";
    const IDIOMS_MODULE: &str = "src/anchor/idioms.rs";
    const RUST_EXTENSION: &str = "rs";
    const TEST_PATH_FRAGMENT: &str = "test";
    const CENTRALIZED_PATTERNS: &[&str] = &[
        "\"DISCRIMINATOR\"",
        "\"discriminator\"",
        "\"CLOSED_ACCOUNT_DISCRIMINATOR\"",
        "\"INIT_SPACE\"",
        "\"declare_id\"",
        "\"declare_id!\"",
        "\"declare_program\"",
        "\"CpiContext\"",
        "\"new_with_signer\"",
        "\"invoke\"",
        "\"reload\"",
        "\"try_deserialize\"",
        "\"try_deserialize_unchecked\"",
        "\"try_from_slice\"",
        "\"deserialize\"",
        "\"from_account_info\"",
        "\"unpack\"",
        "\"unpack_unchecked\"",
        "\"unpack_from_slice\"",
        "\"StateWithExtensions\"",
    ];

    #[test]
    fn emitted_idiom_literals_stay_centralized() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let mut findings = Vec::new();

        for path in rust_sources(&root.join(SOURCE_ROOT)) {
            if !is_scanned_source(&root, &path) {
                continue;
            }
            let relative = path.strip_prefix(&root).unwrap_or(&path);
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("failed to read {}: {error}", relative.display()));
            for pattern in CENTRALIZED_PATTERNS {
                if text.contains(pattern) {
                    findings.push(format!("{} contains {pattern}", relative.display()));
                }
            }
        }

        assert!(
            findings.is_empty(),
            "emitted idiom literals must live in src/anchor/idioms.rs:\n{}",
            findings.join("\n")
        );
    }

    fn rust_sources(root: &Path) -> Vec<PathBuf> {
        let mut paths = Vec::new();
        collect_rust_sources(root, &mut paths);
        paths
    }

    fn collect_rust_sources(path: &Path, paths: &mut Vec<PathBuf>) {
        let Ok(entries) = fs::read_dir(path) else {
            return;
        };
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            if path.is_dir() {
                collect_rust_sources(&path, paths);
            } else {
                paths.push(path);
            }
        }
    }

    fn is_scanned_source(root: &Path, path: &Path) -> bool {
        if path
            .extension()
            .is_none_or(|extension| extension != RUST_EXTENSION)
        {
            return false;
        }
        let relative = path.strip_prefix(root).unwrap_or(path);
        let relative_text = relative.to_string_lossy();
        relative_text != IDIOMS_MODULE && !relative_text.contains(TEST_PATH_FRAGMENT)
    }
}
