[package]
name = "seagrass-sources"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Source adapters for Seagrass framework integrations"

[dependencies]
seagrass-framework = { path = "../seagrass-framework" }
